### ISSUE TITLE
Some identifiers not compatible with version smaller than iOS 9.3

### ISSUE THREAD

**Issue by marcelkalveram** [GregWilson/react-native-apple-healthkit#11]
I recently found this error where the identifier `HKQuantityTypeIdentifierAppleExerciseTime` was crashing the app for iOS versions smaller than 9.3+. Removing that from our fork resolved the issue.

I then checked our log and found a few other ones where it complained about non-supported identifiers, however they didn't seem to crash the app. Not sure which ones exactly but here's list of the files it was generating warnings for:

- RCTAppleHealthKit.o
- RCTAppleHealthKit+Queries.o
- RCTAppleHealthKit+Methods_Nutrition.o
- RCTAppleHealthKit+Utils.o
- RCTAppleHealthKit+Methods_Body.o
- RCTAppleHealthKit+Methods_Results.o
- RCTAppleHealthKit+Methods_Vitals.o
- RCTAppleHealthKit+Methods_Characteristic.o
- RCTAppleHealthKit+TypesAndPermissions.o
- RCTAppleHealthKit+Methods_Fitness.o

**Comment by ambarc** [comment]
We ended up commenting out the line in `RCTAppleHealthKit/RCTAppleHealthKit+TypesAndPermissions.m` and vendoring the lib and *.a file.
