### ISSUE TITLE
Header paths with RN 0.40 causes errors.

### ISSUE THREAD

**Issue by mintuz** [GregWilson/react-native-apple-healthkit#17]
The header paths for React Native libraries have now been namespaced. `#import "RCTBridge.h"` is now `#import <React/RCTBridge.h>`

I am happy to make a PR with the fix :)

**Comment by janstuemmel** [comment]
i had to downgrade to 0.39.2, a fix would be great!

**Comment by MaxMillington** [comment]
Closing this since a PR has been merged
