### ISSUE TITLE
is this repo dead?

### ISSUE THREAD

**Issue by janstuemmel** [GregWilson/react-native-apple-healthkit#19]
there are some useful pr's
most important one for upgrading react native to 0.40.0

**Comment by terrillo** [comment]
I would happily take it over @GregWilson 👍  Already fixed the 0.40 issues

**Comment by MaxMillington** [comment]
@terrillo +1 for taking it over if @GregWilson is no longer working on this.

**Comment by GregWilson** [comment]
I have added

**Comment by GregWilson** [comment]
Sorry for the delay, I have been very busy with other work. I hope to become active on this repo again soon, but in the mean time I have added @terrillo and @MaxMillington as collaborators.

I am open to transferring ownership of the repo / npm if I am unable to keep up with it moving forward.

**Comment by terrillo** [comment]
@GregWilson thanks for adding me as a collaborator! 👍
