### ISSUE TITLE
Publish latest version to npm

### ISSUE THREAD

**Issue by ntharim** [GregWilson/react-native-apple-healthkit#23]
Can we publish the fix for RN v0.40 to npm?

**Comment by MaxMillington** [comment]
@GregWilson Can we give those with write access the ability to publish new versions to npm? https://docs.npmjs.com/cli/owner

**Comment by seanadkinson** [comment]
Mentioned on another issue, but thought I should post here as well:

FYI, I needed this today, so I published to NPM.

    npm install --save react-native-apple-healthkit-rn0.40@0.2.1-2
    react-native link react-native-apple-healthkit-rn0.40

Usage: 

    import AppleHealthKit from 'react-native-apple-healthkit-rn0.40';

**Comment by terrillo** [comment]
@seanadkinson new fork of the same project on NPM. https://www.npmjs.com/package/rn-apple-healthkit. Also please take note of https://github.com/GregWilson/react-native-apple-healthkit/pull/38
