### ISSUE TITLE
Try to run, the error

### ISSUE THREAD

**Issue by TrustTheBoy** [GregWilson/react-native-apple-healthkit#31]
install: `npm install --save react-native-apple-healthkit`
so cd & run `react-native link` and `react-native run-ios` ...
![image](https://cloud.githubusercontent.com/assets/20201085/26188591/ab9c0b38-3bd2-11e7-8b5b-68b78691c01d.png)

![image](https://cloud.githubusercontent.com/assets/20201085/26188706/5105048a-3bd3-11e7-9b98-c6b61dc189d3.png)

**Comment by ital0** [comment]
How did you solve those errors @TrustTheBoy ?
I'm having the same issues here.

**Comment by srshah19** [comment]
any updates on how you solved the issue? Facing the same problem
