### ISSUE TITLE
Build getting failed

### ISSUE THREAD

**Issue by ghost** [GregWilson/react-native-apple-healthkit#36]
I'm using following things:
React Native: **0.46.1**
react-native-apple-healthkit: **0.2.1**

What I did:
I install **react-native-apple-healthkit** 
then I run command:  **react-native link** 
**Problem is:** When I'm running project from Xcode, It's giving me _error : Duplicate interface definition for class "RCTBridge"_

Can anyone please help me on above?

Thanks, In advance.

**Comment by xuyukuan** [comment]
+1

**Comment by janstuemmel** [comment]
maybe try install without react-native link, or downgrade react native ?

**Comment by jgking2** [comment]
@jvarshaprdxn Not sure if you were able to resolve or not, but this has to do with the React Native 
version.  You'll need to go into the node_modules for this project, and update the imports as such: 
--Currently in some of the obj c files.
#import "RCTBridge.h"
#import "RCTEventDispatcher.h"

--Change to this, and it'll work.
#import "React/RCTBridge.h"
#import "React/RCTEventDispatcher.h"

**Comment by yamazaki-sensei** [comment]
@jgking2 Thanks, this seems working fine in my case.

**Comment by terrillo** [comment]
@jvarshaprdxn @xuyukuan new fork of the same project on NPM. https://www.npmjs.com/package/rn-apple-healthkit. Also please take note of https://github.com/GregWilson/react-native-apple-healthkit/pull/38
