### ISSUE TITLE
Workouts, calories and sleep

### ISSUE THREAD

**Issue by MaximeHeckel** [GregWilson/react-native-apple-healthkit#8]
Hi,

Since iOS 10 (maybe before but I've just noticed the change since then) it's possible to get sleep analysis, is it implemented?

Same question concerning calories and workouts

**Comment by GregWilson** [comment]
I have added [getSleepSamples](https://github.com/GregWilson/react-native-apple-healthkit#getsleepsamples) to retrieve sleep samples. It is available on npm releases v0.2.1+

**Comment by MaximeHeckel** [comment]
Thank you, I'll give it a try ASAP!
And concerning workouts? Does Apple allow you to read them?

**Comment by MaximeHeckel** [comment]
Just to get a quick update on this since the issue hasn't been closed, are you currently looking into the workout implementation? If not, I can perhaps dive in the code and try to do it (I'm new to swift/obj-c)

**Comment by henrysik** [comment]
Hi, i would like to ask that is it possible to get calories information such as BasalEnergyBurned and ActiveEnergyBurned for analysis? Thank you!

**Comment by MaximeHeckel** [comment]
@henrysik as far as I've looked it's not yet implemented (as well as the exercise/workout part)
I haven't had the time to dive into the code to contribute sadly but @GregWilson can probably help with that

**Comment by henrysik** [comment]
@MaximeHeckel Thank you!

**Comment by ca** [comment]
@henrysik & @MaximeHeckel see PR https://github.com/GregWilson/react-native-apple-healthkit/pull/29
I implemented it and it's simple enough to fork and do on your own if this PR isn't merged

**Comment by MaximeHeckel** [comment]
@ca nice! this is a great example indeed
I'd love to implement a way to get the workouts

**Comment by markwk** [comment]
Would love to get the Workout Export as well. Still digging into this project among others with react native. 

I'm not sure if this is helpful but here is some iOS code for a workout export app: https://github.com/piscoTech/Workout

**Comment by MaximeHeckel** [comment]
Closing because  it's been more than 3 years and this project is not maintained anymore 🤷‍♂ 🙂
